### ISSUE TITLE
Order Optimization Use Case: Need example of oc start-build command

### ISSUE THREAD

**Issue by pamandrejko** [ibm-cloud-architecture/vaccine-solution-main#21]
Use case doc:
In the [Deploy Debezium CDC Postgres connector ](https://ibm-cloud-architecture.github.io/vaccine-solution-main/use-cases/order/#deploy-debezium-cdc-postgres-connector)section of the use case,  the instructions suggest you run the `oc start-build` command using the output of `oc get build` command, but that does not work.

I ran 
```
oc get build
```
NAME                             TYPE     FROM   STATUS     STARTED          DURATION
connect-cluster-demo-connect-1   Source          Complete   55 minutes ago   47s

then I ran:
```
oc start-build connect-cluster-demo-connect-1 --from-dir vaccine-order-mgr-pg/environment/cdc/connectors --follow
```
Which failed with:
```
Uploading directory "connectors" as binary input for the build ...

Uploading finished
Error from server (NotFound): buildconfigs.build.openshift.io "connect-cluster-demo-connect-1" not found
```

To fix this I had to run this command instead:
```
oc start-build connect-cluster-demo-connect --from-dir ./connectors --follow
```

We should make this more clear, perhaps by providing an example of the command to run.

**Comment by jbcodeforce** [comment]
Added an example
