### ISSUE TITLE
Order Optimization Use Case: pom.xml is hardcoded to 1.4.0.Final

### ISSUE THREAD

**Issue by pamandrejko** [ibm-cloud-architecture/vaccine-solution-main#22]
Doc:
In the [Deploy Debezium CDC Postgres connector instructions](https://ibm-cloud-architecture.github.io/vaccine-solution-main/use-cases/order/#deploy-debezium-cdc-postgres-connector), it says to download the binaries from the folder for the latest version which should be called X.Y.Z.Final. I did that and got version 1.5.0.

I noticed [later in the documentation](https://ibm-cloud-architecture.github.io/vaccine-solution-main/use-cases/order/#behind-the-scenes) where we talk about the[ pom.xml](https://github.com/ibm-cloud-architecture/vaccine-order-mgr-pg/blob/main/pom.xml#L59), that it seems to be hardcoded to use version 1.4.0.

Could this cause a problem?

**Comment by jbcodeforce** [comment]
this is a good catch, now I modified the pom and add a warning note in the instruction.
