### ISSUE TITLE
Order Optimization use case terminology update

### ISSUE THREAD

**Issue by pamandrejko** [ibm-cloud-architecture/vaccine-solution-main#23]
For your consideration:
We are not supposed to use the term `whitelist` anymore, instead we are supposed to use the term `allowlist`

See connector.properties.
https://github.com/ibm-cloud-architecture/vaccine-order-mgr-pg/blob/main/environment/cdc/connector.properties#L5

**Comment by jbcodeforce** [comment]
The property is defined inside of kafka connector so we need to get this fixed in kafka
