### ISSUE TITLE
project name noted in instructions differ from the code which is cloned.

### ISSUE THREAD

**Issue by ibmmark** [ibm-cloud-architecture/vaccine-solution-main#9]
the instructions state:
This will be refered as YOUR_PROJECT_NAME throughout the rest of this tutorial. For the instructions on this tutorial, we use the project name: vaccine-solution

KAFKA_NS to the name of the project where you will deploy Strimzi and the solution (vaccine-solution)
YOUR_PROJECT_NAME to the name of the project (vaccine-solution).

However the project name in the cloned repo all refers to jb-sandbox.

**Comment by jbcodeforce** [comment]
I think this one is fixed with vaccine-solution in script too
